Update Jenkinsfile1.8
Started by user Manisha Ganesh Shinde

Obtained Jenkinsfile from git https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins
 in C:\ProgramData\Jenkins\.jenkins\workspace\MultiThreadGroupsInJmx_Jenkins
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential PT_PipelineToken
 > C:\Program Files\Git\bin\git.exe rev-parse --resolve-git-dir C:\ProgramData\Jenkins\.jenkins\workspace\MultiThreadGroupsInJmx_Jenkins\.git # timeout=10
Fetching changes from the remote Git repository
 > C:\Program Files\Git\bin\git.exe config remote.origin.url https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git # timeout=10
Fetching upstream changes from https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git
 > C:\Program Files\Git\bin\git.exe --version # timeout=10
 > git --version # 'git version 2.49.0.windows.1'
using GIT_ASKPASS to set credentials this is used to fetch github repo from jenkins
 > C:\Program Files\Git\bin\git.exe fetch --tags --force --progress -- https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git +refs/heads/*:refs/remotes/origin/* # timeout=10

 > C:\Program Files\Git\bin\git.exe rev-parse "refs/remotes/origin/main^{commit}" # timeout=10
Checking out Revision 604012379073b4f284423747c1baefada74a187c (refs/remotes/origin/main)
 > C:\Program Files\Git\bin\git.exe config core.sparsecheckout # timeout=10
 > C:\Program Files\Git\bin\git.exe checkout -f 604012379073b4f284423747c1baefada74a187c # timeout=10
Commit message: "Update Jenkinsfile1.7"
 > C:\Program Files\Git\bin\git.exe rev-list --no-walk 093360d6452d653ac548d25ad05212a63c159559 # timeout=10
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential PT_PipelineToken
 > C:\Program Files\Git\bin\git.exe rev-parse "HEAD^{commit}" # timeout=10
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential PT_PipelineToken
[GitCheckoutListener] Recording commits of 'git https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git'
[GitCheckoutListener] Found previous build 'MultiThreadGroupsInJmx_Jenkins #28' that contains recorded Git commits
[GitCheckoutListener] -> Starting recording of new commits since '093360d'
[GitCheckoutListener] -> Single parent commit found - branch is already descendant of target branch head
[GitCheckoutListener] -> Using head commit '6040123' as starting point
[GitCheckoutListener] -> Recorded one new commit
[GitCheckoutListener] -> Git commit decorator successfully obtained 'hudson.plugins.git.browser.GithubWeb@52c735d7' to render commit links
[Pipeline] }

[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Clean Workspace)
[Pipeline] cleanWs
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Deferred wipeout is used...
[WS-CLEANUP] done
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Checkout Code)
[Pipeline] git
Selected Git installation does not exist. Using Default
The recommended git tool is: NONE
using credential PT_PipelineToken
Cloning the remote Git repository
Cloning repository https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git
 > C:\Program Files\Git\bin\git.exe init C:\ProgramData\Jenkins\.jenkins\workspace\MultiThreadGroupsInJmx_Jenkins # timeout=10
Fetching upstream changes from https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git
 > C:\Program Files\Git\bin\git.exe --version # timeout=10
 > git --version # 'git version 2.49.0.windows.1'
using GIT_ASKPASS to set credentials this is used to fetch github repo from jenkins
 > C:\Program Files\Git\bin\git.exe fetch --tags --force --progress -- https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git +refs/heads/*:refs/remotes/origin/* # timeout=10

 > C:\Program Files\Git\bin\git.exe config remote.origin.url https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git # timeout=10
 > C:\Program Files\Git\bin\git.exe config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10

Avoid second fetch
 > C:\Program Files\Git\bin\git.exe rev-parse "refs/remotes/origin/main^{commit}" # timeout=10
Checking out Revision 604012379073b4f284423747c1baefada74a187c (refs/remotes/origin/main)
 > C:\Program Files\Git\bin\git.exe config core.sparsecheckout # timeout=10
 > C:\Program Files\Git\bin\git.exe checkout -f 604012379073b4f284423747c1baefada74a187c # timeout=10
 > C:\Program Files\Git\bin\git.exe branch -a -v --no-abbrev # timeout=10
 > C:\Program Files\Git\bin\git.exe checkout -b main 604012379073b4f284423747c1baefada74a187c # timeout=10
Commit message: "Update Jenkinsfile1.7"
[GitCheckoutListener] Skipping recording, since SCM 'git https://github.com/ManishaS1713/MultiThreadGroupsInJmx_Jenkins.git' already has been processed
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Prepare Thread Values)
[Pipeline] script
[Pipeline] {
[Pipeline] echo
Selected Flows: FishFlow,CatFlow
[Pipeline] echo
Fish: 3, Dog: 0, Cat: 3, Birds: 0, Reptiles: 0
[Pipeline] }

[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Set Environment URL)
[Pipeline] script
[Pipeline] {
[Pipeline] echo
Environment: DEV
[Pipeline] echo
Host: petstore.octoperf.com
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Run Performance Test)
[Pipeline] bat

C:\ProgramData\Jenkins\.jenkins\workspace\MultiThreadGroupsInJmx_Jenkins>IF EXIST MultiThreadGroupsInJmx_Jenkins-result.jtl del MultiThreadGroupsInJmx_Jenkins-result.jtl 

C:\ProgramData\Jenkins\.jenkins\workspace\MultiThreadGroupsInJmx_Jenkins>IF EXIST MultiThreadGroupsInJmx_Jenkins-report rmdir /s /q MultiThreadGroupsInJmx_Jenkins-report 

C:\ProgramData\Jenkins\.jenkins\workspace\MultiThreadGroupsInJmx_Jenkins>C:\Jmeter\apache-jmeter-5.6.3\bin\jmeter.bat -n                 -t MultiThreadGroupsInJmx_Jenkins.jmx                 -Jhost=petstore.octoperf.com                 -JFishFlow_threads=3                 -JDogFlow_threads=0                 -JCatFlow_threads=3                 -JBirdsFlow_threads=0                 -JReptilesFlow_threads=0                 -Jrampup=2                 -Jduration=10                 -l MultiThreadGroupsInJmx_Jenkins-result.jtl                 -e -o MultiThreadGroupsInJmx_Jenkins-report 

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Jmeter/apache-jmeter-5.6.3/lib/log4j-slf4j-impl-2.22.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Jmeter/apache-jmeter-5.6.3/lib/ext/jmeter-agent-2.0.1-jar-with-dependencies.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release
WARN StatusConsoleListener The use of package scanning to locate plugins is deprecated and will be removed in a future release

Creating summariser <summary>
Created the tree successfully using MultiThreadGroupsInJmx_Jenkins.jmx
Starting standalone test @ 2026 Mar 19 21:39:07 IST (1773936547718)
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445

summary =      7 in 00:00:10 =    0.7/s Avg:   652 Min:     1 Max:  1605 Err:     0 (0.00%)
Tidying up ...    @ 2026 Mar 19 21:39:29 IST (1773936569584)
... end of run

[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Generate Summary (P90))

[Pipeline] script
[Pipeline] {
[Pipeline] powershell

[Pipeline] echo
TOTAL=52
P90=1604
ERRORPCT=0
[Pipeline] error
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Publish Report)
Stage "Publish Report" skipped due to earlier failure(s)

[Pipeline] getContext
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Send Email)
Stage "Send Email" skipped due to earlier failure(s)
[Pipeline] getContext
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: ❌ SLA Failed
Finished: FAILURE